### PR TITLE
Add license files

### PR DESCRIPTION
**Pull request by jpmckinney**

### CODE REVIEW

**Comment by jpmckinney** [comment]
Linking https://github.com/wet-boew/wet-boew/issues/7849

**Comment by lucas-hay** [comment]
@mackeym @soyemil Is this OK to merge?

**Comment by mackeym** [comment]
I’m not sure, due to a transition in our work we’ve stopped maintaining the github portion of this.

Lee Soyemi would be the one maintaining it if anyone still is, but as a whole we’re slowly moving away from DNN I believe.

Michael Mackey
Web Developer
Public Works and Government Services Canada / Government of Canada
Travaux publique et Services gouvernementaux Canada / Gouvernement du Canada
michael.mackey@tpsgc-pwgsc.gc.ca<mailto:michael.mackey@tpsgc-pwgsc.gc.ca>

**Comment by mackeym** [comment]
I have not maintained this for at least a couple years now.

From: Michael Mackey
Sent: May-08-17 7:56 AM
To: wet-boew/wet-boew-dotnetnuke <reply@reply.github.com>; wet-boew/wet-boew-dotnetnuke <wet-boew-dotnetnuke@noreply.github.com>
Cc: Mention <mention@noreply.github.com>; Lee Soyemi <Lee.Soyemi@pwgsc-tpsgc.gc.ca>
Subject: RE: [wet-boew/wet-boew-dotnetnuke] Add license files (#5)

I’m not sure, due to a transition in our work we’ve stopped maintaining the github portion of this.

Lee Soyemi would be the one maintaining it if anyone still is, but as a whole we’re slowly moving away from DNN I believe.

Michael Mackey
Web Developer
Public Works and Government Services Canada / Government of Canada
Travaux publique et Services gouvernementaux Canada / Gouvernement du Canada
michael.mackey@tpsgc-pwgsc.gc.ca<mailto:michael.mackey@tpsgc-pwgsc.gc.ca>

**Comment by jpmckinney** [comment]
It should still be possible to merge a couple license files so that others can use and modify it as open source (otherwise, it's just dead code).

**Pull request closed without merging**
